name: Buscar Repositorios

on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Nombre de la organización'
        required: true
        type: string
      query:
        description: 'Término de búsqueda'
        required: true
        type: string

jobs:
  buscar_repositorios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install dotenv node-fetch

      - name: Run backend script
        run: |
          node backend.mjs ${{ github.event.inputs.org }} ${{ github.event.inputs.query }}
        env:
          TOKEN: ${{ secrets.TOKEN }}
