name: Buscar en Repositorios

on:
  repository_dispatch:
    types: [buscar]

jobs:
  ejecutar_busqueda:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar el script de búsqueda
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Aquí no es necesario el token si lo pasamos de forma explícita
        run: node buscar.mjs ${{ github.event.client_payload.org }} ${{ github.event.client_payload.query }}

      - name: Subir resultados
        run: |
          echo "::set-output name=resultados::$(cat resultados.json)"
